spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://49.235.94.2:55435/sqlmate?currentSchema=public&useSSL=false
    password: zmy1qaz2wsx
    username: zmyjust

mybatis-plus:
  global-config:
    db-config:
      insert-strategy: not_empty
      select-strategy: not_empty
      update-strategy: not_empty
      id-type: auto
  type-handlers-package: com.marsh.mpext.common
  mapper-locations: classpath*:/repository/*.xml


jwt:
  alg: HS256
  secret: zmy1234
  issuer: sqlmate


executor:
  pg:
    host: 49.235.94.2
    port: 55435
    database: sqlmate
  mysql:
    host: 49.235.94.2
    port: 3306

sqlexe:
  url: http://49.235.94.2:8081
#  url: http://localhost:8081